# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt\privileges.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PrivilegesWindow(object):
    def setupUi(self, PrivilegesWindow):
        PrivilegesWindow.setObjectName("PrivilegesWindow")
        PrivilegesWindow.resize(564, 362)
        self.centralwidget = QtWidgets.QWidget(PrivilegesWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 521, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblTables = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.lblTables.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lblTables.setObjectName("lblTables")
        self.horizontalLayout.addWidget(self.lblTables)
        self.cbTables = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.cbTables.setObjectName("cbTables")
        self.horizontalLayout.addWidget(self.cbTables)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 60, 521, 80))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblSelect = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblSelect.setObjectName("lblSelect")
        self.verticalLayout.addWidget(self.lblSelect)
        self.lblInsert = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblInsert.setObjectName("lblInsert")
        self.verticalLayout.addWidget(self.lblInsert)
        self.lblUpdate = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblUpdate.setObjectName("lblUpdate")
        self.verticalLayout.addWidget(self.lblUpdate)
        self.lblTruncate = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblTruncate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblTruncate.setObjectName("lblTruncate")
        self.verticalLayout.addWidget(self.lblTruncate)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblDelete = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblDelete.setObjectName("lblDelete")
        self.verticalLayout_3.addWidget(self.lblDelete)
        self.lblReferences = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblReferences.setObjectName("lblReferences")
        self.verticalLayout_3.addWidget(self.lblReferences)
        self.lblTrigger = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.lblTrigger.setObjectName("lblTrigger")
        self.verticalLayout_3.addWidget(self.lblTrigger)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.tblAttributes = QtWidgets.QTableWidget(self.centralwidget)
        self.tblAttributes.setGeometry(QtCore.QRect(20, 150, 521, 192))
        self.tblAttributes.setObjectName("tblAttributes")
        self.tblAttributes.setColumnCount(5)
        self.tblAttributes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblAttributes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAttributes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAttributes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAttributes.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblAttributes.setHorizontalHeaderItem(4, item)
        PrivilegesWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PrivilegesWindow)
        QtCore.QMetaObject.connectSlotsByName(PrivilegesWindow)

    def retranslateUi(self, PrivilegesWindow):
        _translate = QtCore.QCoreApplication.translate
        PrivilegesWindow.setWindowTitle(_translate("PrivilegesWindow", "Privilegios"))
        self.lblTables.setText(_translate("PrivilegesWindow", "Tablas:"))
        self.lblSelect.setText(_translate("PrivilegesWindow", "Select:"))
        self.lblInsert.setText(_translate("PrivilegesWindow", "Insert:"))
        self.lblUpdate.setText(_translate("PrivilegesWindow", "Update:"))
        self.lblTruncate.setText(_translate("PrivilegesWindow", "Truncate:"))
        self.lblDelete.setText(_translate("PrivilegesWindow", "Delete:"))
        self.lblReferences.setText(_translate("PrivilegesWindow", "References:"))
        self.lblTrigger.setText(_translate("PrivilegesWindow", "Trigger:"))
        item = self.tblAttributes.horizontalHeaderItem(0)
        item.setText(_translate("PrivilegesWindow", "Atributo"))
        item = self.tblAttributes.horizontalHeaderItem(1)
        item.setText(_translate("PrivilegesWindow", "Select"))
        item = self.tblAttributes.horizontalHeaderItem(2)
        item.setText(_translate("PrivilegesWindow", "Insert"))
        item = self.tblAttributes.horizontalHeaderItem(3)
        item.setText(_translate("PrivilegesWindow", "Update"))
        item = self.tblAttributes.horizontalHeaderItem(4)
        item.setText(_translate("PrivilegesWindow", "References"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PrivilegesWindow = QtWidgets.QMainWindow()
    ui = Ui_PrivilegesWindow()
    ui.setupUi(PrivilegesWindow)
    PrivilegesWindow.show()
    sys.exit(app.exec_())
